### PR TITLE
UPDATED: jupyterLab.func.sh output_proxy_executioner warning

### PR DESCRIPTION
**Pull request by Axlfc**
#129

### CODE REVIEW

**Review by AleixMT — CHANGES_REQUESTED** [review]
It is an error, not a warning. The customizer exits, so it is an error, which is not recuperable

**Comment by Axlfc** [comment]
Do not close the pull request yet, there is an error with the desktop launcher.

**Comment by AleixMT** [comment]
> Do not close the pull request yet, there is an error with the desktop launcher.

You already solved the issue that you described: 

> ERROR: The function output_proxy_executioner does not recognize 0 as a valid argument

Create a new issue. Stop mixing. Stick to what you planned.

**Review by AleixMT — CHANGES_REQUESTED** [review]
Delete the exit, is not needed. Exitting the app is handled by output proxy

**Review by Axlfc — COMMENTED** [review]
exit removed due to output_proxy_executioner already does it.

**Review by AleixMT — APPROVED** [review]

**Pull request merged**
